#!/bin/bash
set -eo pipefail

source scripts/req/setup

curl -X POST ${DOMAIN}/tasks?user_id=${TEST_USER_ID} \
   -H 'Content-Type: application/json' \
   -d '{
            "label":"First Weighted Task",
            "weight": 2.0
        }'