#!/bin/bash
set -eo pipefail

# Check if LOCAL is true
if [ "$REMOTE" = "true" ]; then
    DOMAIN="https://a8hmbfh87l.execute-api.us-east-1.amazonaws.com"
else
    DOMAIN="http://127.0.0.1:3000"
fi

# Print the DOMAIN variable to verify
echo "Making requests to: $DOMAIN"

export DOMAIN

export TEST_USER_ID=245678