AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Random Tasks Application
  
Globals:
  Function:
    Timeout: 10

Resources:
  RandomTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: function.handler
      Runtime: nodejs18.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RandomTasksTable
      Events:
        CreateTask:
          Type: HttpApi
          Properties:
            Path: /tasks
            Method: POST
        GetTask:
          Type: HttpApi
          Properties:
            Path: /tasks/{id}
            Method: GET
        GetTasks:
          Type: HttpApi
          Properties:
            Path: /tasks
            Method: GET
        GetRandomTask:
          Type: HttpApi
          Properties:
            Path: /tasks/random
            Method: GET
        PatchTask:
          Type: HttpApi
          Properties:
            Path: /tasks/{id}
            Method: PATCH
        UserSignIn:
          Type: HttpApi
          Properties:
            Path: /users/signin
            Method: POST

  RandomTasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: random-tasks
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

Outputs:
  ApiEndpoint:
    Description: "The invoke URL for our HTTP API"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/tasks"
  Function:
    Description: "Random Tasks function ARN"
    Value: !GetAtt RandomTasksFunction.Arn
